# HTTP & SSL
quarkus.http.ssl-port=8443
quarkus.http.port=8443
quarkus.http.insecure-requests=disabled
quarkus.http.ssl.certificate.key-files=key.pem
quarkus.http.ssl.certificate.files=cert.pem
quarkus.http.ssl.certificate.key-store-file-type=PEM
quarkus.oidc.tls.verification=none

# CORS (Keep only if frontend is on a different port/domain)
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=https://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.access-control-allow-credentials=true
quarkus.http.cors.exposed-headers=Content-Disposition


# OIDC Core (Authorization Code Flow + PKCE in BFF)
quarkus.oidc.auth-server-url=https://localhost:9443/realms/oauth2-playbook
quarkus.oidc.client-id=oauth2-playbook-auth-code-bff-pkce
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.pkce-required=true
#quarkus.oidc.authentication.scopes=openid,profile,email
quarkus.oidc.authentication.scopes=profile users:read


quarkus.http.auth.permission.health.paths=/q/health/*
quarkus.http.auth.permission.health.policy=permit
quarkus.oidc.logout.post-logout-path=https://localhost:3000
quarkus.http.auth.permission.login.paths=/login
quarkus.http.auth.permission.login.policy=authenticated

quarkus.oidc.authentication.cookie-path=/
quarkus.oidc.authentication.cookie-same-site=lax
quarkus.oidc.logout.path=/logout

#quarkus.oidc.authentication.redirect-path=/callback
quarkus.oidc.authentication.restore-path-after-redirect=true
#quarkus.oidc.authentication.fail-with-http-401=true
quarkus.oidc.authentication.java-script-auto-redirect=false


# Token Management (store all tokens in encrypted session cookie)
quarkus.oidc.token-state-manager.strategy=keep-all-tokens
quarkus.oidc.token-state-manager.encryption-secret=pAQuZNBQTL4uEaGX2AjZxKslkh+5vUEGPIXdxmvcEA0=

# Token propagation to downstream resource server
# quarkus.oidc.token-propagation.enabled=true

# Resource Client
quarkus.rest-client.resource-api.url=https://localhost:15443
quarkus.rest-client.resource-api.trust-all=true
quarkus.tls.trust-all=true